#
# makefile
# Copyright (C) 2018 Marius Greuel. All rights reserved.
#

BOARD ?= BOARD_ARDUINO_MICRO

ATL_PATH = atl
TARGET = hidrcjoy
SOURCES = hidrcjoy.cpp

include atl/boards.mk
include atl/avr8.mk
