#
# makefile
# Copyright (C) 2018 Marius Greuel. All rights reserved.
#

BOARD ?= BOARD_ARDUINO_MICRO

ATL_PATH = atl
TARGET = rc2usb
SOURCES = rc2usb.cpp

include atl/boards.mk
include atl/avr8.mk
